# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.7
before_install:
 - sudc apt-get update
 - sudo apt-get install python-pyside
 - sudo aptitude install --force-yes --yes python-wxgtk2.8
 - pip install ply --use-mirrors
 - pip install cython --use-mirrors
 - pip install casuarius --use-mirrors
 - pip install traits --use-mirrors

before_script:
 - ln -s /usr/lib/pymodules/python2.7/PySide /home/vagrant/virtualenv/python2.7/lib/python2.7/site-packages/PySide -v
 - ln -s /usr/lib/pymodules/python2.7/wx /home/vagrant/virtualenv/python2.7/lib/python2.7/site-packages/wx -v

script: python setup.py test
notifications:
  email: 
    - dpinte@enthought.com
